/// Generic Dimensions
const MARGIN_SMALL = 4.0;
const MARGIN_MEDIUM = 8.0;
const MARGIN_CARD_MEDIUM_2 = 12.0;
const MARGIN_MEDIUM_2 = 16.0;
const MARGIN_MEDIUM_3 = 20.0;
const MARGIN_LARGE = 24.0;
const MARGIN_XLARGE = 32.0;
const MARGIN_XXLARGE = 48.0;

const TEXT_HEADING_1X = 24.0;
const TEXT_HEADING_2X = 28.0;
const TEXT_BIG = 32.0;
const TEXT_REGULAR = 14.0;
const TEXT_REGULAR_2X = 16.0;
const TEXT_CARD_REGULAR_2X = 18.0;
const TEXT_REGULAR_3X = 20.0;
const TEXT_SMALL_2 = 11.0;
const TEXT_SMALL = 8.0;

/// App Specific
const BOT_NAV_HEIGHT = 70.0;
const CHAT_HISTORY_ITEM_HEIGHT = 85.0;
const CHAT_HISTORY_ITEM_PROFILE_RADIUS = 35.0;
const SEARCH_BAR_HEIGHT = 70.0;
const CONTACTS_FEATURES_BAR_HEIGHT = 115.0;
const CONTACT_ITEM_VIEW_HEIGHT = 80.0;
const CONTACT_ITEM_PROFILE_RADIUS = 30.0;
const CONTACT_ALPHABET_TOP_BAR_HEIGHT = 40.0;
